services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    container_name: frontend

  backend:
    build: ./backend
    ports:
      - 8000:8000
    container_name: backend
